services:
  ollama:
    image: docker.io/ollama/ollama:latest
    ports:
      - "${PORT}:11434"
    volumes:
      # - .:/code
      # - ./ollama/ollama:/root/.ollama
      - ${OLLAMA_MODELS}:/root/.ollama
      - ${OLLAMA_CODE}:/code
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    environment:
      - OLLAMA_HOST=${OLLAMA_HOST}
      - OLLAMA_KEEP_ALIVE=${OLLAMA_KEEP_ALIVE}
      - CUDA_VISIBLE_DEVICES=${GPU_ID}
      - NVIDIA_VISIBLE_DEVICES=${GPU_ID}
    # 최신 Docker Compose 플러그인에서는 아래 GPU 예약이 동작합니다.
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["${GPU_ID}"]
              capabilities: [gpu]
    networks:
      - ollama-docker

  ollama-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: ollama-webui
    volumes:
      - ./ollama/ollama-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - 8080:8080
    environment: # https://docs.openwebui.com/getting-started/env-configuration#default_models
      - OLLAMA_BASE_URLS=http://host.docker.internal:7869 #comma separated ollama hosts
      - ENV=dev
      - WEBUI_AUTH=False
      - WEBUI_NAME=valiantlynx AI
      - WEBUI_URL=http://localhost:8080
      - WEBUI_SECRET_KEY=t0p-s3cr3t
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    networks:
      - ollama-docker

networks:
  ollama-docker:
    external: false
  