apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gce-slow
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gce-fast
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd

---
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: vol-disk-01

spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: slow
