apiVersion: v1
kind: Service
metadata:
  name: jupyterlab1
  labels:
    name: jupyterlab1
spec:
  type: LoadBalancer
  ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
      name: http
  selector:
    name: jupyterlab1
---
apiVersion: v1
kind: Service
metadata:
  name: jupyterlab2
  labels:
    name: jupyterlab2
spec:
  type: LoadBalancer
  ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
      name: http
  selector:
    name: jupyterlab2
