- name: RedHat > Copying files.
  copy:
    src: "~/ca.crt"
    dest: "/etc/pki/ca-trust/source/anchors"
  when: ansible_facts['os_family'] in ["RedHat", "CentOS", "Rocky"]
  
- name: Ubuntu > Copying files.
  copy:
    src: "~/ca.crt"
    dest: "/usr/local/share/ca-certificates"
  when: ansible_facts['os_family'] in ["Debian", "Ubuntu"]

- name: RedHat > Make sure our master-node trusts this CA
  shell: |
    update-ca-trust \
    && systemctl restart k3s-agent
  when:
    - inventory_hostname in groups["nodes"]
    - ansible_facts['os_family'] in ["RedHat", "CentOS", "Rocky"]

- name: Ubuntu > Make sure our master-node trusts this CA
  shell: |
    update-ca-certificates \
    && systemctl restart k3s-agent
  when:
    - inventory_hostname in groups["nodes"]
    - ansible_facts['os_family'] in ["Debian", "Ubuntu"]

- name: RedHat > Make sure our master-node trusts this CA
  shell: |
    update-ca-trust \
    && systemctl restart k3s
  when:
    - inventory_hostname in groups["masters"]
    - ansible_facts['os_family'] in ["RedHat", "CentOS", "Rocky"]

- name: Ubuntu > Make sure our master-node trusts this CA
  shell: |
    update-ca-certificates \
    && systemctl restart k3s
  when:
    - inventory_hostname in groups["masters"]
    - ansible_facts['os_family'] in ["Debian", "Ubuntu"]

