services:
  jupyterlab-torch-2.7:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USERNAME=rsnet
        - IMAGE_BASE=nvidia/cuda:12.8.1-cudnn-devel-ubuntu22.04
        - VERSION_PYTHON=3.11
        - VERSION_NUMPY=1.26.4
        - VERSION_JUPYTERLAB=4.1.7
        - VERSION_SKLEARN=1.4.2
        - VERSION_TRANSFORMERS=4.52.3
        - VERSION_XFORMERS=0.0.30
        - VERSION_TRL=0.17.0
    image: nockchun/jupyterlab-torch:2.7
    container_name: gupyterlab
    restart: unless-stopped
    volumes:
      - /data/nfshare/notebook:/notebook
      - /data/nfshare/notebook_data:/data
    ports:
      - "8888:8888"
      - "6006:6006"
      - "8081:8080"
    command:
      jupyter lab --notebook-dir=/notebook --no-browser --ip=0.0.0.0 --allow-root --NotebookApp.token="rsnet"

