- name: Add Helm Repository
  become: false
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: "https://charts.jetstack.io"

- name: Install Cert Manager Chart
  become: false
  kubernetes.core.helm:
    name: cert-manager
    chart_ref: jetstack/cert-manager
    release_namespace: cert-manager
    create_namespace: true
    release_values:
      installCRDs: true

- name: Wait for pods to come up
  become: false
  shell: kubectl get pods -n cert-manager -o json | jq '.items | map(select(.status.phase != "Running")) | length'
  register: kubectl_get_pods
  until: kubectl_get_pods.stdout == "0"
  retries: 60
  delay: 10
