version: '3.4'

services:
  11.8-tf2.11-torch2.0:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BASE_IMAGE=nvidia/cuda:12.2.0-devel-ubuntu22.04
        - VERSION_PYTHON=3.10
        - NB_USER=rsnet
        - NB_UID=1000
        - NB_GID=100
        - TF_VERSION=2.11
    environment:
      GRANT_SUDO: "yes"
      JUPYTER_ENABLE_LAB: "yes"
      NB_UID: ${JUPYTER_UID:-1000}
      NB_GID: ${JUPYTER_GID:-1000}
    image: nockchun/jupyterlab-gpu-devel:11.8-tf2.11-torch2.0
    volumes:
      - /data/notebook:/notebook
      - /data/notebook_data:/data
    ports:
      - "8888:8888"
    command:
      jupyter lab --notebook-dir=/notebook --no-browser --ip=0.0.0.0 --allow-root --NotebookApp.token='rsnet'
      # start-notebook.sh
      # sleep infinity
