version: '3.4'

services:
  11.8.0-torch2.0_tf2.10:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BASE_IMAGE=nockchun/miniconda-gpu-devel:11.8.0-py_3.9
        - USER=rsnet
        - USER_UID=1000
        - LIB_PYTHON=lib-11.8.0_torch2.0.yml
        - TF_VERSION=2.10.0
    image: nockchun/ray-gpu:11.8.0-torch2.0_tf2.11
    command:
      jupyter lab --notebook-dir=/notebook --no-browser --ip=0.0.0.0 --allow-root --NotebookApp.token='rsnet'
    networks:
      - rsnet
    ports:
      - "8888:8888"

  11.4.3-torch1.13_tf2.10:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BASE_IMAGE=nockchun/miniconda-gpu-devel:11.4.3-py_3.9
        - USER=rsnet
        - USER_UID=1000
        - LIB_PYTHON=lib-11.4.3_torch1.13.yml
        - TF_VERSION=2.10.0
    image: nockchun/ray-gpu:11.4.3-torch1.13_tf2.10
    command:
      jupyter lab --notebook-dir=/notebook --no-browser --ip=0.0.0.0 --allow-root --NotebookApp.token='rsnet'
    networks:
      - rsnet
    ports:
      - "8888:8888"


networks:
  rsnet:
    driver: bridge
