services:
  jupyterlab-torch-2.7:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USERNAME=rsnet
        - IMAGE_BASE=nvidia/cuda:12.8.1-cudnn-devel-ubuntu24.04
        - VERSION_MINICONDA=latest
        - VERSION_PYTHON=3.10
        - VERSION_NUMPY=1.26.4
        - VERSION_PYTORCH=2.7.0
    image: nockchun/jupyterlab-torch:2.7
    container_name: jupyterlab
    restart: unless-stopped
    volumes:
      - /data/nfshare/notebook:/notebook
      - /data/nfshare/notebook_data:/data
    ports:
      - "8888:8888"
      - "6006:6006"
      - "8081:8080"
    command:
      jupyter lab --notebook-dir=/notebook --no-browser --ip=0.0.0.0 --allow-root --NotebookApp.token="rsnet"
