services:
  jupyterlab-torch-2.7:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USERNAME=rsnet
        - IMAGE_BASE=nvidia/cuda:12.6.3-cudnn-devel-ubuntu22.04
        - VERSION_MINICONDA=latest
        - VERSION_PYTHON=3.10
        - VERSION_NUMPY=1.26.4
        - VERSION_TF=2.19.0
        - VERSION_PYTORCH=2.7.0
        - PYTORCH=true
    image: nockchun/jupyterlab-torch:2.7
    container_name: jupyterlab
    restart: unless-stopped
    volumes:
      - /home/daeun/nfshare/notebook:/root/projects
      - /home/daeun/nfshare/notebook_data:/data
    ports:
      - "8889:80"
      # - "6006:6006"
      # - "8081:8080"
    command:
      jupyter lab --notebook-dir=/notebook --no-browser --ip=0.0.0.0 --allow-root --NotebookApp.token="rsnet"
