version: '3.4'

services:
  11.8.0-torch2.0_tf2.12:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BASE_IMAGE=nockchun/jupyterlab-gpu-devel:11.8.0-py_3.10
        - LIB_PYTHON=lib-11.8.0_torch2.0_tf2.11.yml
        - TF_VERSION=2.12.0
    environment:
      GRANT_SUDO: "yes"
      JUPYTER_ENABLE_LAB: "yes"
      NB_UID: ${JUPYTER_UID:-1000}
      NB_GID: ${JUPYTER_GID:-1000}
    image: nockchun/ml-gpu:11.8-torch2.0_tf2.12
    command:
      jupyter lab --notebook-dir=/notebook --no-browser --ip=0.0.0.0 --allow-root --NotebookApp.token='rsnet'
    networks:
      - rsnet
    ports:
      - "8888:8888"
    volumes:
      - /data/notebook:/notebook
      - /data/notebook_data:/data

networks:
  rsnet:
    driver: bridge
