- name: Check Install Commands For HA-Extra K3s
  debug:
    msg: "{{ lookup('template', 'extra.j2') }}"

- name: Install HA-Extra For K3s
  shell: |
    {{ lookup('template', 'extra.j2') }}
  args:
    warn: false

- name: Install Kubectl Auto-Complete
  shell: |
    kubectl completion bash > /etc/bash_completion.d/kubectl \
    && source /usr/share/bash-completion/bash_completion
  args:
    warn: false
    executable: /bin/bash
  
- name: Set kubernetes environments for user
  become: false
  shell: |
    mkdir -p ~/.kube \
    && kubectl config view --raw >~/.kube/config \
    && chmod 600 ~/.kube/config
  args:
    warn: false
