- name: Register number of GPU processors
  shell: lspci 2>/dev/null | grep VGA|grep NVIDIA | wc -l
  register: gpu_count

- name: Install K3s Master
  import_tasks: master.yml
  when:
    - "'master' in groups"
    - inventory_hostname in groups["master"]

# - name: Register the server token
#   command: cat /var/lib/rancher/k3s/server/node-token
#   register: k3s_token
#   when:
#     - "'master' in groups"
#     - inventory_hostname in groups["master"]

- name: Install K3s HA-Master
  import_tasks: extra.yml
  when:
    - "'extra' in groups"
    - inventory_hostname in groups["extra"]



