- name: Add Helm Repository
  become: false
  kubernetes.core.helm_repository:
    name: nfs-provisioner
    repo_url: "https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner"

- name: Install NFS-Provisioner Chart
  become: false
  kubernetes.core.helm:
    name: nfs-provisioner
    chart_ref: nfs-provisioner/nfs-subdir-external-provisioner
    release_namespace: nfs-provisioner
    create_namespace: true
    release_values:
      nfs:
        server: "{{ service_nfs.server_host }}"
        path: "{{ service_nfs.share_path }}"

- name: Wait for pods to come up
  become: false
  shell: kubectl get pods -n nfs-provisioner -o json | jq '.items | map(select(.status.phase != "Running")) | length'
  register: kubectl_get_pods
  until: kubectl_get_pods.stdout == "0"
  retries: 60
  delay: 10