apiVersion: v1
kind: Service
metadata:
  name: svc-mongodb
spec:
  selector:
    app: mongodb
  ports:
  - name: connection
    protocol: TCP
    targetPort: 27017
    port: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express
spec:
  selector:
    app: mongo-express
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    targetPort: 8081
    port: 8081
    nodePort: 30000
