version: "3.3"

services:
  neo4j:       
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_shell_enabled=true
    volumes:
      - /neo4j/import:/import
      - /neo4j/data:/data
      - /neo4j/conf:/conf
      - /neo4j/logs:/logs
      - /neo4j/plugins:/plugins
