apiVersion: v1
kind: Pod
metadata:
  name: gluster-demo-pod
  namespace: rsnet-demo
  labels:
    name: gluster-demo-pod
spec:
  containers:
  - name: gluster-demo-pod
    image: nockchun/docterm:latest
    ports:
    - name: web
      containerPort: 80
    volumeMounts:
    - name: gluster-vol1
      mountPath: /gvol
      readOnly: false
  volumes:
  - name: gluster-vol1
    persistentVolumeClaim:
      claimName: gluster-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gluster-claim
  namespace: rsnet-demo
spec:
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gluster-default-volume 
  namespace: rsnet-demo
  annotations:
    pv.beta.kubernetes.io/gid: "1000" 
spec:
  capacity:
    storage: 2Gi 
  accessModes: 
    - ReadWriteMany
  glusterfs:
    endpoints: glusterfs-cluster 
    path: vol_gluster 
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: Service
metadata:
  name: glusterfs-cluster
  namespace: rsnet-demo
spec:
  ports:
  - port: 1
---
apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-cluster
  namespace: rsnet-demo
subsets:
  - addresses:
      - ip: 10.10.1.111
    ports:
      - port: 1
  - addresses:
      - ip: 10.10.1.112
    ports:
      - port: 1
  - addresses:
      - ip: 10.10.1.113
    ports:
      - port: 1
  - addresses:
      - ip: 10.10.1.114
    ports:
      - port: 1
