services:
  postgresql:
    image: docker.io/bitnami/postgresql:17
    ports:
      - '5432:5432'
    volumes:
      - '/data/postgres:/bitnami/postgresql'
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=postgres
      - POSTGRESQL_USERNAME=rsnet
      - POSTGRESQL_PASSWORD=rsnet
      - POSTGRESQL_DATABASE=rsnet

