- hosts: all
  connection: local
  serial: 1
  gather_facts: no
  become: false

  tasks:
    - command: ssh-keyscan -t ecdsa {{ ansible_host }}
      register: keyscan_ip
    
    - command: ssh-keyscan -t ecdsa {{ inventory_hostname }}
      register: keyscan_hostname
    
    - lineinfile:
        path: ~/.ssh/known_hosts
        create: yes
        line: "{{ item }}"
      with_items:
        - "{{ keyscan_ip.stdout_lines }}"

    - lineinfile:
        path: ~/.ssh/known_hosts
        create: yes
        line: "{{ item }}"
      with_items:
        - "{{ keyscan_hostname.stdout_lines }}"
    