version: "3.4"

services:
    jupyterlab.cpu:
        build:
            context: ./jupyterlab
            dockerfile: Dockerfile
        image: jupyterlab.cpu
        container_name: jupyterlab.cpu
        hostname: labcpu
        restart: always
        network_mode: host
        env_file:
            - ./jupyterlab/.env
        ports:
            - "8889:8888"
        #     - "8022:22"
        #     - "6006:6006"
        #     - "8786:8786"
        #     - "8787:8787"
        volumes:
            - /data/notebooks:/notebooks
            - /data/tensorboard:/tensorboard
        command:
            jupyter lab --no-browser --ip=0.0.0.0 --allow-root --NotebookApp.token='rsnet'
