version: "3.3"

services:
    scheduler:
        build:
            context: ./dask
            dockerfile: Dockerfile
        image: dask
        container_name: scheduler
        hostname: dask-scheduler
        network_mode: host
        # ports:
        #     - "8786:8786"
        #     - "8787:8787"
        env_file:
            - ./dask/.env
        command: ["dask-scheduler"]

    worker:
        build:
            context: ./dask
            dockerfile: Dockerfile
        image: dask
        container_name: worker
        hostname: dask-worker
        network_mode: host
        volumes:
            - /data/notebooks:/notebooks
        env_file:
            - ./dask/.env
        command: ["dask-worker", "tcp://localhost:8786"]
