apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoweb
  labels:
    app: demoweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demoweb
  template:
    metadata:
      labels:
        app: demoweb
    spec:
      containers:
      - name: nginx-demoweb
        image: nginx
        ports:
        - containerPort: 80
