- name: Add Helm Repository
  become: false
  kubernetes.core.helm_repository:
    name: bitnami
    repo_url: "https://charts.bitnami.com/bitnami"

- name: Make Namespace
  become: false
  shell: |
    kubectl create namespace redis

- name: Make Local Volume
  become: false
  shell: |
    cat << EOF | kubectl apply -f -
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: locvol-redis
      namespace: redis
    spec:
      storageClassName: local-path
      resources:
        requests:
          storage: {{ kube_redis.storage }}
      accessModes:
        - ReadWriteOnce
    EOF

- name: Install Redis Chart
  become: false
  kubernetes.core.helm:
    name: redis
    chart_ref: bitnami/redis
    release_namespace: redis
    release_values:
      global:
        redis:
          password: "{{ kube_redis.password }}"
      persistence:
        existingClaim: "locvol-redis"

- name: Wait for pods to come up
  become: false
  shell: kubectl get pods -n redis -o json | jq '.items | map(select(.status.phase != "Running")) | length'
  register: kubectl_get_pods
  until: kubectl_get_pods.stdout == "0"
  retries: 60
  delay: 10

- name: Make Develop Service
  become: false
  shell: |
    cat << EOF | kubectl apply -f -
    apiVersion: v1
    kind: Service
    metadata:
      name: redis-dev
      namespace: redis
    spec:
      type: LoadBalancer
      ports:
        - port: {{ kube_redis.port_expose }}
          targetPort: 6379
          protocol: TCP
      selector:
        app.kubernetes.io/instance: redis
        app.kubernetes.io/name: redis
    EOF
  when: 
    - k3s_cluster.mode != 'product'