version: '3.4'

services:
  cpu-dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USERNAME=kwp
        - PASSWORD=1234!@#$qwer
        - uid=1000
        - gid=1000
        - VERSION_BASE=nockchun/miniconda-cpu-devel:py3.9
        - LIB_PYTHON=lib_cpu
    image: registry.k3s.lab/devcontainer:cpu-build001
    command:
      sleep infinity

  cuda11.0.3_tf2.4_torch1.7:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USERNAME=kwp
        - PASSWORD=1234!@#$qwer
        - uid=1000
        - gid=1000
        - VERSION_BASE=nockchun/miniconda-gpu-devel:11.0.3-py3.9
        - LIB_PYTHON=lib_gpu-tf2.4-torch1.7
    image: registry.k3s.lab/devcontainer:cuda11.0.3_tf2.4_torch1.7-build1
    command:
      sleep infinity

  cuda11.3.1_tf2.4_torch1.7:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USERNAME=kwp
        - PASSWORD=1234!@#$qwer
        - uid=1000
        - gid=1000
        - VERSION_BASE=nockchun/miniconda-gpu-devel:11.3.1-py3.9
        - LIB_PYTHON=lib_gpu-tf2.6-torch1.11
    image: registry.k3s.lab/devcontainer:cuda11.3.1_tf2.4_torch1.7-build1
    command:
      sleep infinity
