- name: Create Master Node
  import_tasks: master.yml
  when: 
    - "'ha' not in k3s_cluster.mode"
    - inventory_hostname in groups["master"]

- name: Pause for 1 minutes for k3s startup
  pause:
    minutes: 1
  when: inventory_hostname in groups["master"]

- name: Install calico cni
  import_tasks: calico.yml
  when:
    - inventory_hostname in groups["master"]
    - "'default' not in k3s_cluster.mode|string"

- name: Wait for pods to come up
  become: false
  shell: kubectl get pods --all-namespaces -o json | jq '.items | map(select(.status.phase != "Running")) | length'
  register: kubectl_get_pods
  until: kubectl_get_pods.stdout == "0"
  retries: 30
  delay: 30
  when: inventory_hostname in groups["master"]

- name: Install k3s nodes without docker
  shell: |
    curl -sfL https://get.k3s.io | \
    K3S_URL=https://{{ groups["master"][0] }}:6443 K3S_TOKEN={{ hostvars[groups["master"][0]]['k3s_token'].stdout }} sh -s -
  when: 
    - inventory_hostname in groups["node"]
    - hostvars[inventory_hostname]['docker_installed'] is not defined

- name: Install k3s nodes with docker
  shell: |
    curl -sfL https://get.k3s.io | \
    K3S_URL=https://{{ groups["master"][0] }}:6443 K3S_TOKEN={{ hostvars[groups["master"][0]]['k3s_token'].stdout }} sh -s - --docker
  when: 
    - inventory_hostname in groups["node"]
    - hostvars[inventory_hostname]['docker_installed'] is defined

