### Install K3S #########################################################################
- name: Create default(flannel, svclb) CPU Version
  shell: |
    curl -sfL https://get.k3s.io | \
    K3S_KUBECONFIG_MODE="644" \
    INSTALL_K3S_EXEC="--disable=traefik --cluster-cidr=10.42.0.0/16" sh -s -
  register: master_log
  when:
    - "k3s_cluster.mode|string == 'default'"
    - hostvars[inventory_hostname]['gpu_count'].stdout|int == 0

- name: Create default(flannel, svclb) GPU Version
  shell: |
    curl -sfL https://get.k3s.io | \
    K3S_KUBECONFIG_MODE="644" \
    INSTALL_K3S_EXEC="--disable=traefik --cluster-cidr=10.42.0.0/16" sh -s - --docker
  register: master_log
  when:
    - "k3s_cluster.mode|string == 'default'"
    - hostvars[inventory_hostname]['gpu_count'].stdout|int > 0

- name: Create develop(calico, svclb) CPU & GPU Version
  shell: |
    curl -sfL https://get.k3s.io | \
    K3S_KUBECONFIG_MODE="644" \
    INSTALL_K3S_EXEC="--flannel-backend=none --disable-network-policy --disable=traefik --cluster-cidr=10.42.0.0/16" sh -s - --docker
  register: master_log
  when:
    - "k3s_cluster.mode|string == 'develop'"

- name: Create product(calico) CPU Version
  shell: |
    curl -sfL https://get.k3s.io | \
    K3S_KUBECONFIG_MODE="644" \
    INSTALL_K3S_EXEC="--flannel-backend=none --disable-network-policy --disable=servicelb --disable=traefik --cluster-cidr=10.42.0.0/16" sh -s -
  register: master_log
  when:
    - "k3s_cluster.mode|string == 'product'"
    - hostvars[inventory_hostname]['gpu_count'].stdout|int == 0

- name: Create product(calico) GPU Version
  shell: |
    curl -sfL https://get.k3s.io | \
    K3S_KUBECONFIG_MODE="644" \
    INSTALL_K3S_EXEC="--flannel-backend=none --disable-network-policy --disable=servicelb --disable=traefik --cluster-cidr=10.42.0.0/16" sh -s - --docker
  register: master_log
  when:
    - "k3s_cluster.mode|string == 'product'"
    - hostvars[inventory_hostname]['gpu_count'].stdout|int > 0

### Install Others ######################################################################
- name: Install Kubectl Auto-Complete
  shell: |
    kubectl completion bash > /etc/bash_completion.d/kubectl \
    && source /usr/share/bash-completion/bash_completion
  args:
    executable: /bin/bash
  
- name: Set kubernetes environments for user
  become: false
  shell: |
    mkdir -p ~/.kube \
    && kubectl config view --raw >~/.kube/config \
    && chmod 600 ~/.kube/config

- name: Register the server token
  command: cat /var/lib/rancher/k3s/server/node-token
  register: k3s_token
