version: '3.4'

services:
  11.3.1-py_3.9:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USERNAME=kwp
        - PASSWORD=1234!@#$qwer
        - UID=1000
        - GID=1000
        - VERSION_CUDA=11.3.1-runtime-ubuntu20.04
        - VERSION_MINICONDA=latest
        - VERSION_PYTHON=3.9
    image: registry.k3s.lab/miniconda-gpu-runtime:11.3.1-py3.9
    command:
      sleep infinity
  
  11.0.3-py_3.9:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USERNAME=kwp
        - PASSWORD=1234!@#$qwer
        - UID=1000
        - GID=1000
        - VERSION_CUDA=11.0.3-devel-ubuntu20.04
        - VERSION_MINICONDA=latest
        - VERSION_PYTHON=3.9
    image: registry.k3s.lab/miniconda-gpu-runtime:11.0.3-py3.9
    command:
      sleep infinity
