services:
  gupyterlab-tf-torch:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USERNAME=rsnet
        - IMAGE_BASE=nvidia/cuda:12.6.3-cudnn-devel-ubuntu22.04
        - VERSION_MINICONDA=latest
        - VERSION_PYTHON=3.10
        - VERSION_NUMPY=1.26.4
        - VERSION_TF=2.17.0
        - VERSION_PYTORCH=2.5.0
        - PYTORCH=true
    image: nockchun/gupyterlab-tf-torch:2.17-2.6.0
    container_name: gupyterlab
    volumes:
      - /data/nfshare/notebook:/notebook
      - /data/nfshare/notebook_data:/data
    ports:
      - "8888:8888"
      - "6006:6006"
      - "8081:8080"
    command:
      jupyter lab --notebook-dir=/notebook --no-browser --ip=0.0.0.0 --allow-root --NotebookApp.token="rsnet"

  gupyterlab-tf-torch-k3s:
    image: nockchun/gupyterlab-tf-torch:2.17-2.6.0
    container_name: gupyterlab-k3s
    volumes:
      - /data/nfshare/jupyter-nfs-vol-notebook-pvc-da22fb6b-37e0-404a-ac62-7a97956f5e88:/notebook
      - /data/nfshare/jupyter-nfs-vol-data-pvc-f862b73d-11fa-4acd-813b-98a620a18733:/data
    ports:
      - "9999:8888"
    command:
      jupyter lab --notebook-dir=/notebook --no-browser --ip=0.0.0.0 --allow-root --NotebookApp.token="rsnet"
