apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: demoweb-tls
spec:
  secretName: demoweb-tls
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
  commonName: demoweb-system
  dnsNames:
  - ingress.demo.com
  