apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/secure-backends: "true"
    ingress.kubernetes.io/ssl-passthrough: "true"
    #nginx.org/ssl-backend: "kubernetes-dashboard"
    kubernetes.io/ingress.allow-http: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "100M"
  name: demoweb-ingress
spec:
  tls:
  - hosts:
    - ingress.demo.com
    secretName: demoweb-tls
  rules:
  - host: ingress.demo.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: demoweb
            port:
              number: 80
