apiVersion: v1
kind: Pod
metadata:
  name: docterm01
  namespace: rsnet-demo
spec:
  containers:
  - name: docterm
    image: nockchun/docterm:latest
    ports:
    - containerPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: docterm02
  namespace: rsnet-demo
spec:
  containers:
  - name: docterm
    image: nockchun/docterm:latest
    ports:
    - containerPort: 80
