version: "3.4"

services:
    jupyterlab:
        # build:
        #     context: ./jupyterlab.kubeflow
        #     dockerfile: Dockerfile
        image: nockchun/jupyterlab.kubeflow:2.2.1
        container_name: jupyterlab.kubeflow
        hostname: jupyterlab
        restart: always
        # network_mode: host
        ports:
            - "8888:8888"
            - "6006:6006"
        networks:
            - rsnet
        volumes:
            - /data/notebooks:/home/jovyan
            - /data/notebooks/ml_data:/ml_data
            - /data/notebooks/tensorboard:/tensorboard
        command:
            jupyter lab --no-browser --ip=0.0.0.0 --allow-root --NotebookApp.token='rsnet'

networks:
    rsnet:
        driver: bridge