version: "3.4"

services:
    jupyterlab:
        # build:
        #     context: ./jupyterlab.gpu
        #     dockerfile: Dockerfile
        image: nockchun/jupyterlab.gpu:1.0
        container_name: jupyterlab.gpu
        hostname: jupyterlab
        restart: always
        # network_mode: host
        ports:
            - "8888:8888"
            - "6006:6006"
        networks:
            - rsnet
        volumes:
            - /data/notebooks:/notebooks
            - /data/notebooks/ml_data:/ml_data
            - /data/notebooks/tensorboard:/tensorboard
        command:
            jupyter lab --notebook-dir=/notebooks --no-browser --ip=0.0.0.0 --allow-root --NotebookApp.token='rsnet'

networks:
    rsnet:
        driver: bridge