version: "3.4"

services:
    jupyterlab.cpu:
        build:
            context: ./machinelearning/cpu
            dockerfile: Dockerfile
        image: jupyterlab.cpu
        container_name: jupyterlab.cpu
        hostname: jupyterlab
        restart: always
        # network_mode: host
        env_file:
            - ./jupyterlab/.env
        ports:
            - "8888:8888"
            - "6006:6006"
            - "8786:8786"
            - "8787:8787"
        networks:
            - rsnet
        volumes:
            - /data/notebooks:/notebooks
            - /data/notebooks/ml_data:/ml_data
            - /data/notebooks/tensorboard:/tensorboard
        command:
            jupyter lab --no-browser --ip=0.0.0.0 --allow-root --NotebookApp.token='rsnet'

networks:
    rsnet:
        driver: bridge