services:
  extension:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - IMAGE_BASE=bitnami/postgresql:17.0.0
        - VERSION_PGVECTOR=v0.7.4
    image: nockchun/postgresql_pgvector:17.0.0_0.7.4
