name: base
channels:
  - conda-forge
dependencies:
  - elasticsearch
  - pyspark
  - sparkmagic
  - matplotlib
  - seaborn
  - celery
  - cufflinks-py
  - hdf5
  - html5lib
  - ipytest
  - more-itertools
  - nltk
  - numexpr
  - pandas-datareader
  - openpyxl
  - xlrd
  - xlsxwriter
  - xlwt
  - pillow
  - protobuf
  - pydot
  - pydotplus
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - spacy
  - sqlalchemy
  - statsmodels
  - sympy
  - opencv
  - pyvirtualdisplay
  - google-resumable-media
  - dill
  - pandas
  - httplib2
  - nodejs
  - jupyterlab
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
  - widgetsnbextension
  - ipykernel
  - pyyaml
  - networkx
  - graphviz
  - python-graphviz
  - pyflakes
  - autopep8
  - ipywidgets
  - tensorflow-gpu==2.2
  - kfp
  - beautifulsoup4
  - cython
  - psycopg2
  - pandas-profiling
  - jupyterlab-git
  
