name: base
channels:
  - anaconda
  - bioconda
dependencies:
  - matplotlib
  - seaborn
  - celery
  # - ray
  # - ray[rllib]
  - pip:
    - modin
    - modin[ray]
    - tfx
    - apache-beam
  #   - gym
  #   - gym[atari]
