version: '3.4'

services:
  11.8.0-py3.9:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USERNAME=rsnet
        - PASSWORD=rsnet
        - UID=1000
        - GID=1000
        - VERSION_CUDA=11.8.0-devel-ubuntu22.04
        - VERSION_MINICONDA=latest
        - VERSION_PYTHON=3.9
    image: nockchun/miniconda-gpu-devel:11.8.0-py3.9
    command:
      sleep infinity
  
  11.0.3-py3.9:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USERNAME=rsnet
        - PASSWORD=rsnet
        - UID=1000
        - GID=1000
        - VERSION_CUDA=11.0.3-devel-ubuntu20.04
        - VERSION_MINICONDA=latest
        - VERSION_PYTHON=3.9
    image: nockchun/miniconda-gpu-devel:11.0.3-py3.9
    command:
      sleep infinity
