name: base
channels:
  - conda-forge
dependencies:
  - jupyterlab
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
  - widgetsnbextension
  - ipykernel
  - pyyaml
  - jupyterlab-git
  - ipywidgets
  - ipytest
  - seaborn
  - hdf5
  - html5lib
  - more-itertools
  - statsmodels
  - sympy
  - opencv
  - pyvirtualdisplay
  - google-resumable-media
  - dill
  - pandas
  - httplib2
  - nodejs
  - protobuf
  - pydot
  - pydotplus
  - scikit-image
  - scikit-learn
  - scipy
  - kfp
  - spacy
  - sqlalchemy
  - networkx
  - graphviz
  - python-graphviz
  - pyflakes
  - autopep8
  - beautifulsoup4
  - cython
  - psycopg2
  - pandas-profiling
  - pyarrow
  - nltk
  - numexpr
  - pandas-datareader
  - openpyxl
  - xlrd
  - xlsxwriter
  - xlwt
  - pillow
  - pyspark
  - matplotlib
  - elasticsearch
  - sparkmagic
  - celery
  - tensorflow-gpu
  - tensorboard
  - ipympl
  - nltk
  - pip
  - pip:
    - tensorflow-addons
    - gensim
    - ray
