version: "3.5"

services:
    api:
        build:
            context: ./api
            dockerfile: Dockerfile
        image: api
        container_name: api
        hostname: api
        restart: unless-stopped
        volumes:
            - /data/api:/app
        ports:
            - "5000:5000"
        networks:
            - rsnet

    postgres:
        image: postgres
        container_name: postgres
        hostname: postgres
        restart: unless-stopped
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
            PGDATA: ${POSTGRES_PASSWORD:-/data/postgres}
        volumes:
            - /data/postgres:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - rsnet

networks:
    rsnet:
        driver: bridge