services:
  gupyterlab-tf-torch:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USERNAME=rsnet
        - IMAGE_BASE=tensorflow/tensorflow:2.17.0-gpu
        - VERSION_MINICONDA=latest
        - VERSION_PYTHON=3.10
        - VERSION_TF=2.17.1
        - PYTORCH=true
    image: nockchun/gupyterlab-tf-torch:2.17-2.5.1
    container_name: gupyterlab3
    volumes:
      # - /data/notebook:/notebook
      # - /data/notebook_data:/data
      - /data/nfshare/notebook:/notebook
      - /data/nfshare/notebook_data:/data
    ports:
      - "9999:8888"
      # - "6006:6006"
    command:
      jupyter lab --notebook-dir=/notebook --no-browser --ip=0.0.0.0 --allow-root --NotebookApp.token="rsnet"
