name: base
channels:
  - conda-forge
dependencies:
  - jupyterlab
  - jupyter_console
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
  - widgetsnbextension
  - ipykernel
  - pyyaml
  - jupyterlab-git
  - ipywidgets
  - ipytest
  - seaborn
  - hdf5
  - html5lib
  - more-itertools
  - statsmodels
  - sympy
  - opencv
  - pyvirtualdisplay
  - dill
  - pandas
  - httplib2
  - nodejs
  - protobuf
  - pydot
  - pydotplus
  - scikit-image
  - scikit-learn
  - scipy
  - sqlalchemy
  - networkx
  - graphviz
  - python-graphviz
  - pyflakes
  - autopep8
  - beautifulsoup4
  - cython
  - psycopg2
  - pandas-profiling
  - pyarrow
  - numexpr
  - pandas-datareader
  - openpyxl
  - xlrd
  - xlsxwriter
  - xlwt
  - pillow
  - pyspark
  - matplotlib
  - elasticsearch
  - sparkmagic
  - celery
  - tensorflow-gpu
  - tensorboard
  - tensorflow-datasets
  - ipympl
  - bqplot
  - jupyterlab-drawio
  - airflow
  - gym-all
  - pyopengl
  - nltk
  - asyncpg
  - bokeh
  - jupyter_bokeh
  - python-language-server
  - r-languageserver
  - chktex
  - jupyterlab-lsp
  - texlab
  - dm-tree
  - starlette
  - uvicorn
  - typing-extensions
  - ray-all
  - fastapi
  - ta-lib
  - plotly
  - dash
  - jupyter-dash
  - tortoise-orm
  # - elyra
  - pip
  - pip:
    - lz4
    - bokeh
    - tensorflow-addons
    # - ray
    - modin[ray]
    - nengo-dl
    - nengo[all]
    - gym-notebook-wrapper
    - opencv-python
    - neptune-notebooks
