version: '3.4'

services:
  11.7.1-tf2.6_torch1.12:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USERNAME=rsnet
        - PASSWORD=rsnet
        - UID=1000
        - GID=1000
        - VERSION_BASE=nockchun/miniconda-gpu-devel:11.7.1-py3.9
        - LIB_PYTHON=lib-11.7.1_tf2.6_torch1.12
    image: nockchun/jupyterlab-gpu:11.7.1-tf2.7_torch1.12_build12
    command:
      jupyter lab --notebook-dir=/notebooks --no-browser --ip=0.0.0.0 --allow-root --NotebookApp.token='rsnet'
    networks:
      - rsnet
    ports:
      - "8888:8888"

  11.0.3-tf2.4_torch1.7:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USERNAME=rsnet
        - PASSWORD=rsnet
        - UID=1000
        - GID=1000
        - VERSION_BASE=nockchun/miniconda-gpu-devel:11.0.3-py3.9
        - LIB_PYTHON=lib-11.0.3_tf2.4_torch1.7
    image: nockchun/jupyterlab-gpu:11.0.3-tf2.4_torch1.7_build6
    # command:
    #   sleep infinity
    command:
      jupyter lab --notebook-dir=/notebooks --no-browser --ip=0.0.0.0 --allow-root --NotebookApp.token='rsnet'
    networks:
      - rsnet
    ports:
      - "8888:8888"

networks:
  rsnet:
    driver: bridge
